import yaml
from autogen_core.models import UserMessage
from src import FileHelper
from src import ModelHelper


async def buildAgent(prompt: str, output_file: str, model_name: str, provider: str, api_key: str, agent_name: str = None) -> str:
    """
    Builds an agent YAML configuration from a prompt description using an LLM.

    :param prompt: Description of what the agent should do.
    :param output_file: Path to save the agent YAML file.
    :param model_name: Name of the model to use.
    :param provider: Provider of the model (e.g. 'openai', 'azure-openai').
    :param api_key: API key or env reference (e.g. 'env:OAI_API_KEY').
    :param agent_name: Optional name for the agent; generated by LLM if not provided.
    :return: Path to the saved YAML file.
    """
    # Resolve API key (handle env: references) for LLM calls only
    resolved_config = FileHelper.interpretYamlModelObject({"name": model_name, "provider": provider, "api-key": api_key})
    llm = ModelHelper.createModel(resolved_config["name"], resolved_config["provider"], resolved_config["api-key"])

    # Use the LLM to craft a proper system prompt for the agent
    system_prompt_response = await llm.create([
        UserMessage(
            content=(
                "You are an expert at designing AI agents. "
                "Based on the following description, create a detailed system prompt for an AI assistant. "
                "Only output the system prompt, nothing else.\n\n"
                f"Description: {prompt}"
            ),
            source="user"
        )
    ])
    system_prompt = system_prompt_response.content

    # Generate an agent name if not provided
    if not agent_name:
        name_response = await llm.create([
            UserMessage(
                content=(
                    "Give a short, concise name (2-3 words max) for an AI agent with this description: "
                    f"{prompt}. Only output the name, nothing else."
                ),
                source="user"
            )
        ])
        agent_name = name_response.content.strip()

    # Build the YAML structure, preserving the original api-key reference (e.g. env:XXX)
    agent_config = {
        "name": agent_name,
        "model": {
            "name": model_name,
            "provider": provider,
            "api-key": api_key,
        },
        "prompt": system_prompt,
    }

    # Save to YAML file
    with open(output_file, "w", encoding="utf-8") as f:
        yaml.dump(agent_config, f, allow_unicode=True, default_flow_style=False)

    return output_file
